"""empty message

Revision ID: 30463433f493
Revises: 6a3910dd4049
Create Date: 2018-12-03 01:33:48.050643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30463433f493'
down_revision = '6a3910dd4049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'athlete', 'fantasy', ['fantasy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athlete', type_='foreignkey')
    # ### end Alembic commands ###
