"""empty message

Revision ID: 5c56a7d2c6b7
Revises: cd434b5a4ec6
Create Date: 2018-11-25 21:39:22.048362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c56a7d2c6b7'
down_revision = 'cd434b5a4ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('conference', 'conference_name')
    op.add_column('university', sa.Column('mascot', sa.String(length=120), nullable=True))
    op.add_column('university', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('university', 'university_name')
    op.drop_column('university', 'university_mascot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('university_mascot', sa.VARCHAR(length=120), nullable=True))
    op.add_column('university', sa.Column('university_name', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('university', 'name')
    op.drop_column('university', 'mascot')
    op.add_column('conference', sa.Column('conference_name', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('conference', 'name')
    # ### end Alembic commands ###
