"""empty message

Revision ID: 8d1933edb09b
Revises: 826dcaf06bd2
Create Date: 2018-11-27 09:30:25.963963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1933edb09b'
down_revision = '826dcaf06bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('bats', sa.Enum('R', 'L', 'S', name='bats_throws'), nullable=True))
    op.add_column('athlete', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('athlete', sa.Column('position', sa.Enum('P', 'ChildProcessError', 'INF', 'OF', name='position'), nullable=True))
    op.add_column('athlete', sa.Column('throws', sa.Enum('R', 'L', 'S', name='bats_throws'), nullable=True))
    op.add_column('athlete', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete', 'weight')
    op.drop_column('athlete', 'throws')
    op.drop_column('athlete', 'position')
    op.drop_column('athlete', 'number')
    op.drop_column('athlete', 'height')
    op.drop_column('athlete', 'bats')
    # ### end Alembic commands ###
