"""empty message

Revision ID: 8f39c6c7e851
Revises: 6a3910dd4049
Create Date: 2018-11-28 01:46:05.697355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f39c6c7e851'
down_revision = '6a3910dd4049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=120), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('mascot', sa.String(length=120), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('athlete', sa.Column('fantasy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'athlete', 'fantasy', ['fantasy_id'], ['id'])
    op.add_column('staff', sa.Column('fantasy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'fantasy', ['fantasy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'fantasy_id')
    op.drop_constraint(None, 'athlete', type_='foreignkey')
    op.drop_column('athlete', 'fantasy_id')
    op.drop_table('fantasy')
    # ### end Alembic commands ###
