"""Athlete table

Revision ID: b8e33ee6ff12
Revises: eb17f10e1ee2
Create Date: 2018-11-24 17:35:29.092572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e33ee6ff12'
down_revision = 'eb17f10e1ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('DOB', sa.String(length=11), nullable=False),
    sa.Column('enrollment_date', sa.String(length=11), nullable=True),
    sa.Column('scholarship_amount', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=120), nullable=True),
    sa.Column('university_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name', 'DOB')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete')
    # ### end Alembic commands ###
