"""empty message

Revision ID: cd434b5a4ec6
Revises: eaf3ae7d0b91
Create Date: 2018-11-25 21:37:22.097245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd434b5a4ec6'
down_revision = 'eaf3ae7d0b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('image_path', sa.String(length=1000), nullable=True))
    op.add_column('staff', sa.Column('image_path', sa.String(length=1000), nullable=True))
    op.add_column('university', sa.Column('image_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'image_path')
    op.drop_column('staff', 'image_path')
    op.drop_column('conference', 'image_path')
    # ### end Alembic commands ###
